### ISSUE TITLE
Tinc_hostupd vs mainline tinc

### ISSUE THREAD

**Issue by Azulinho** [siblynx/tinc-1.0.16_hostupd#1]
Are you keeping this fork up to date with the latest stable branch of Tinc ?
The repo name mentions 1.0.16 but I see that you have a few recent commits in here

this is good shit

**Comment by siblynx** [comment]
No, as embedded version number suggests, I stuck with 1.0.16 version. It is base of my personal network, and the code is a dump so anyone can port the thing to other versions of Tinc (possibly into 1.1).

Recent commit is probably tag, but if you count others, then they're only my "hostupd" modifications and some backports noted in commit messages separately.

If you have any other questions, feel free to reopen.
